### PR TITLE
Add event classes to auth

### PR DESCRIPTION
**Pull request by HerbertIV**
#91 
Work in progress

### CODE REVIEW

**Comment by qunabu** [comment]
imho this is DRY case 

what about 
```php
<?php

namespace EscolaLms\Auth\Events;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

abstract class EscolaLmsAccountTemplate
{
    use Dispatchable, SerializesModels;

    private Authenticatable $user;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Authenticatable $user)
    {
        $this->user = $user;
    }

    public function getUser(): Authenticatable
    {
        return $this->user;
    }
}
```

then 
```php 
<?php
namespace EscolaLms\Auth\Events;

class EscolaLmsAccountConfirmedTemplate extends EscolaLmsAccountTemplate { 
  //... 
}
```

also the name **Template** is confusing because those are **Events** not Templates 

Other potential issue, `Event` will be serialised so we would rather not serialise not `user` object but `user_id` is enought, @pa-cholek what is your opinion on that ?

**Comment by pa-cholek** [comment]
Templates event listener depends on events having `getUser()` which returns either model or id of user; 

Serializing whole Models is ok though, because SerializesModels trait transforms Models into Illuminate\Contracts\Database\ModelIdentifier class (which holds minimum required informations about the Model)

**Review by pa-cholek — CHANGES_REQUESTED** [review]
As @qunabu mentioned, DRY, just create one abstract event (so that no one accidentaly dispatches it) and have every other event extended from it

**Review by qunabu — CHANGES_REQUESTED** [review]
Please fix DRY

**Review by qunabu — APPROVED** [review]

**Pull request merged**
